name: gendiff_check

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          pip install poetry flake8 pytest
          make install
      - name: Run linter
        run: make lint
      - name: Code Coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 8dd63d5e3f081b78f9f488bbf12df35269b8eaeb15307415653cf88c7dfa5008
        with:
          coverageCommand: make test-coverage
          debug: true
