name: gendiff_check

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install gnome-keyring
        run: |
          sudo apt install gnome-keyring
      - name: Install poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          make install
      - name: Run linter
        run: |
          make lint
      - name: Run tests
        run: |
          make check
      - name: Create Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Test
        run: |
          make test-coverage
      - name: Sending Reporter
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_REPORTER_ID }}
        run: |
          ./cc-test-reporter after-build -r "$GITHUB_TOKEN"
